[build]
  command = "bash netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/nominatim/*"
  to = "https://nominatim.openstreetmap.org/:splat"
  status = 200
  force = true
  headers = {User-Agent = "AURA Weather Route App (https://aura-app.netlify.app)", Accept = "application/json"}

[[redirects]]
  from = "/osrm/*"
  to = "https://router.project-osrm.org/:splat"
  status = 200
  force = true
  headers = {Accept = "application/json"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
